// packages/magic-move/src/solid/ShikiMagicMoveRenderer.tsx
/** @jsxImportSource solid-js */

import type { JSX } from 'solid-js'
import type { KeyedTokensInfo, MagicMoveRenderOptions } from '../types'
import { createEffect, createSignal } from 'solid-js'
import { MagicMoveRenderer as Renderer } from '../renderer'
import { normalizeCSSProperties } from './utils'

export interface ShikiMagicMoveRendererProps {
  animate?: boolean
  tokens: KeyedTokensInfo
  previous?: KeyedTokensInfo
  options?: MagicMoveRenderOptions
  onStart?: () => void
  onEnd?: () => void
  class?: string
  style?: JSX.CSSProperties
}

/**
 * A wrapper component to `MagicMoveRenderer`
 */
export function ShikiMagicMoveRenderer(props: ShikiMagicMoveRendererProps) {
  let container!: HTMLPreElement
  let renderer: Renderer
  const [isMounted, setIsMounted] = createSignal(false)

  createEffect(() => {
    if (!container)
      return
    // Remove previous content
    container.innerHTML = ''
    setIsMounted(true)
    renderer = new Renderer(container)
  })

  createEffect(() => {
    async function render() {
      if (!renderer)
        return

      Object.assign(renderer.options, props.options)
      if (props.animate === undefined || props.animate === true) {
        if (props.previous)
          renderer.replace(props.previous)

        props.onStart?.()
        await renderer.render(props.tokens)
        props.onEnd?.()
      }
      else {
        renderer.replace(props.tokens)
      }
    }

    render()
  })

  return (
    <pre
      ref={container}
      class={`shiki-magic-move-container ${props.class || ''}`.trim()}
      style={props.style}
    >
      {
        // Render initial tokens for SSR
      }
      <div>
        {isMounted()
          ? undefined
          : props.tokens?.tokens.map((token) => {
              if (token.content === '\n')
                return <br />

              return (
                <span
                  style={{
                    ...normalizeCSSProperties(token.htmlStyle),
                    color: token.color,
                  }}
                  class={['shiki-magic-move-item', token.htmlClass]
                    .filter(Boolean)
                    .join(' ')}
                >
                  {token.content}
                </span>
              )
            })}
      </div>
    </pre>
  )
}

// packages/magic-move/src/svelte/ShikiMagicMoveRenderer.svelte
<script lang='ts'>
  import type { KeyedTokensInfo, MagicMoveRenderOptions } from '@shikijs/magic-move/types'
  import { MagicMoveRenderer } from '@shikijs/magic-move/renderer'

  interface ShikiMagicMoveRendererProps {
    class?: string
    animate?: boolean
    tokens: KeyedTokensInfo
    previous?: KeyedTokensInfo
    options?: MagicMoveRenderOptions
    onStart?: () => void
    onEnd?: () => void
  }

  const {
    animate = true,
    tokens,
    previous,
    options,
    onStart,
    onEnd,
    ...props
  }: ShikiMagicMoveRendererProps = $props()

  let container: HTMLPreElement
  let renderer: MagicMoveRenderer
  let isMounted = $state(false)

  $effect(() => {
    if (!container)
      return
    // eslint-disable-next-line svelte/no-dom-manipulating -- hand off ownership of `container` to MagicMoveRenderer
    container.innerHTML = ''
    isMounted = true
    renderer = new MagicMoveRenderer(container)
  })

  $effect(() => {
    async function render() {
      if (!renderer)
        return
      Object.assign(renderer.options, options)
      if (animate) {
        if (previous)
          renderer.replace(previous)
        onStart?.()
        await renderer.render(tokens)
        onEnd?.()
      }
      else {
        renderer.replace(tokens)
      }
    }
    render()
  })
</script>

<pre bind:this={container} class='shiki-magic-move-container {props?.class}' {...props}>
  <!-- render initial tokens for SSR -->
  {#if !isMounted}
    {#each tokens.tokens as token (token.key)}
      {#if token.content === '\n'}
        <br />
      {/if}
      <span
        class='shiki-magic-move-item'
        style:color={token.color}
        style={token.htmlStyle}>
        {token.content}
      </span>
    {/each}
  {/if}
</pre>
