// packages/magic-move/src/solid/ShikiMagicMoveRenderer.tsx
/** @jsxImportSource solid-js */

import type { JSX } from 'solid-js'
import type { KeyedTokensInfo, MagicMoveRenderOptions } from '../types'
import { createEffect, createSignal } from 'solid-js'
import { MagicMoveRenderer as Renderer } from '../renderer'
import { normalizeCSSProperties } from './utils'

export interface ShikiMagicMoveRendererProps {
  animate?: boolean
  tokens: KeyedTokensInfo
  previous?: KeyedTokensInfo
  options?: MagicMoveRenderOptions
  onStart?: () => void
  onEnd?: () => void
  class?: string
  style?: JSX.CSSProperties
}

/**
 * A wrapper component to `MagicMoveRenderer`
 */
export function ShikiMagicMoveRenderer(props: ShikiMagicMoveRendererProps) {
  let container!: HTMLPreElement
  let renderer: Renderer
  const [isMounted, setIsMounted] = createSignal(false)

  createEffect(() => {
    if (!container)
      return
    // Remove previous content
    container.innerHTML = ''
    setIsMounted(true)
    renderer = new Renderer(container)
  })

  createEffect(() => {
    async function render() {
      if (!renderer)
        return

      Object.assign(renderer.options, props.options)
      if (props.animate === undefined || props.animate === true) {
        if (props.previous)
          renderer.replace(props.previous)

        props.onStart?.()
        await renderer.render(props.tokens)
        props.onEnd?.()
      }
      else {
        renderer.replace(props.tokens)
      }
    }

    render()
  })

  return (
    <pre
      ref={container}
      class={`shiki-magic-move-container ${props.class || ''}`.trim()}
      style={props.style}
    >
      {
        // Render initial tokens for SSR
      }
      <div>
        {isMounted()
          ? undefined
          : props.tokens?.tokens.map((token) => {
              if (token.content === '\n')
                return <br />

              return (
                <span
                  style={{
                    ...normalizeCSSProperties(token.htmlStyle),
                    color: token.color,
                  }}
                  class={['shiki-magic-move-item', token.htmlClass]
                    .filter(Boolean)
                    .join(' ')}
                >
                  {token.content}
                </span>
              )
            })}
      </div>
    </pre>
  )
}

// packages/magic-move/src/react/ShikiMagicMoveRenderer.tsx
import type { KeyedTokensInfo, MagicMoveRenderOptions } from '../types'
import * as React from 'react'
import { MagicMoveRenderer as Renderer } from '../renderer'
import { normalizeCSSProperties } from './utils'

export interface ShikiMagicMoveRendererProps {
  animate?: boolean
  tokens: KeyedTokensInfo
  previous?: KeyedTokensInfo
  options?: MagicMoveRenderOptions
  onStart?: () => void
  onEnd?: () => void
  className?: string
  style?: React.CSSProperties
}

/**
 * A wrapper component to `MagicMoveRenderer`
 */
export function ShikiMagicMoveRenderer(
  {
    animate = true,
    tokens,
    previous,
    options,
    onStart,
    onEnd,
    className,
    style,
  }: ShikiMagicMoveRendererProps,
) {
  const container = React.useRef<HTMLPreElement>(null)
  const renderer = React.useRef<Renderer>(null)
  const [isMounted, setIsMounted] = React.useState(false)

  React.useEffect(() => {
    if (!container.current)
      return
    // Remove previous content
    container.current.innerHTML = ''
    setIsMounted(true)
    renderer.current = new Renderer(container.current)
  }, [])

  React.useEffect(() => {
    async function render() {
      if (!renderer.current)
        return
      Object.assign(renderer.current.options, options)
      if (animate) {
        if (previous)
          renderer.current.replace(previous)

        onStart?.()
        await renderer.current.render(tokens)
        onEnd?.()
      }
      else {
        renderer.current.replace(tokens)
      }
    }

    render()
    // FIXME: we should only re-render when tokens change, but react-hooks rule doesn't allow.
    // Try to correct the dependency array if something goes wrong.
  }, [tokens])

  return (
    <pre
      ref={container}
      className={`shiki-magic-move-container ${className || ''}`.trim()}
      style={style}
    >
      {
        // Render initial tokens for SSR

        // FIXME: Remove this element
        // Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
      }
      <div>
        {isMounted
          ? undefined
          : tokens.tokens.map((token) => {
              if (token.content === '\n')
                return <br key={token.key} />

              return (
                <span
                  style={{
                    ...normalizeCSSProperties(token.htmlStyle),
                    color: token.color,
                  }}
                  className={['shiki-magic-move-item', token.htmlClass].filter(Boolean).join(' ')}
                  key={token.key}
                >
                  {token.content}
                </span>
              )
            })}
      </div>
    </pre>
  )
}
