// packages/magic-move/src/solid/ShikiMagicMoveRenderer.tsx
/** @jsxImportSource solid-js */

import type { JSX } from 'solid-js'
import type { KeyedTokensInfo, MagicMoveRenderOptions } from '../types'
import { createEffect, createSignal } from 'solid-js'
import { MagicMoveRenderer as Renderer } from '../renderer'
import { normalizeCSSProperties } from './utils'

export interface ShikiMagicMoveRendererProps {
  animate?: boolean
  tokens: KeyedTokensInfo
  previous?: KeyedTokensInfo
  options?: MagicMoveRenderOptions
  onStart?: () => void
  onEnd?: () => void
  class?: string
  style?: JSX.CSSProperties
}

/**
 * A wrapper component to `MagicMoveRenderer`
 */
export function ShikiMagicMoveRenderer(props: ShikiMagicMoveRendererProps) {
  let container!: HTMLPreElement
  let renderer: Renderer
  const [isMounted, setIsMounted] = createSignal(false)

  createEffect(() => {
    if (!container)
      return
    // Remove previous content
    container.innerHTML = ''
    setIsMounted(true)
    renderer = new Renderer(container)
  })

  createEffect(() => {
    async function render() {
      if (!renderer)
        return

      Object.assign(renderer.options, props.options)
      if (props.animate === undefined || props.animate === true) {
        if (props.previous)
          renderer.replace(props.previous)

        props.onStart?.()
        await renderer.render(props.tokens)
        props.onEnd?.()
      }
      else {
        renderer.replace(props.tokens)
      }
    }

    render()
  })

  return (
    <pre
      ref={container}
      class={`shiki-magic-move-container ${props.class || ''}`.trim()}
      style={props.style}
    >
      {
        // Render initial tokens for SSR
      }
      <div>
        {isMounted()
          ? undefined
          : props.tokens?.tokens.map((token) => {
              if (token.content === '\n')
                return <br />

              return (
                <span
                  style={{
                    ...normalizeCSSProperties(token.htmlStyle),
                    color: token.color,
                  }}
                  class={['shiki-magic-move-item', token.htmlClass]
                    .filter(Boolean)
                    .join(' ')}
                >
                  {token.content}
                </span>
              )
            })}
      </div>
    </pre>
  )
}

// packages/magic-move/src/web-component/ShikiMagicMoveRenderer.ts
import type { KeyedTokensInfo, MagicMoveRenderOptions } from '../types'
import { MagicMoveRenderer as Renderer } from '../renderer'

export class ShikiMagicMoveRenderer extends HTMLElement {
  private _animated: boolean = true
  private _tokens!: KeyedTokensInfo
  private _previous?: KeyedTokensInfo
  private _options?: MagicMoveRenderOptions
  private _class: string = ''

  get animated() {
    return this._animated
  }

  set animated(value: boolean) {
    this._animated = value
    this.propertyChangedCallback()
  }

  get tokens() {
    return this._tokens
  }

  set tokens(value: KeyedTokensInfo) {
    this._tokens = value
    this.propertyChangedCallback()
  }

  get previous(): KeyedTokensInfo | undefined {
    return this._previous
  }

  set previous(value: KeyedTokensInfo) {
    this._previous = value
    this.propertyChangedCallback()
  }

  get options(): MagicMoveRenderOptions | undefined {
    return this._options
  }

  set options(value: MagicMoveRenderOptions | undefined) {
    this._options = value
    if (this.renderer)
      Object.assign(this.renderer.options, this.options)
    this.propertyChangedCallback()
  }

  get class() {
    return this._class
  }

  set class(value: string) {
    this._class = value
    this.propertyChangedCallback()
  }

  private container?: HTMLPreElement

  private renderer?: Renderer

  private batchUpdate = false

  private hasUpdated = false

  constructor() {
    super()
  }

  connectedCallback() {
    this.container = document.createElement('pre')
    this.container.classList.add('shiki-magic-move-container')
    this.container.className += ` ${this.class}`

    this.renderer = new Renderer(this.container)
    this.renderer.render(this.tokens)

    this.appendChild(this.container)
  }

  propertyChangedCallback() {
    if (!this.batchUpdate) {
      this.batchUpdate = true

      setTimeout(() => {
        this.batchUpdate = false

        if (!this.hasUpdated) {
          this.hasUpdated = true
          return
        }

        if (this.renderer)
          this.transform()
      }, 0)
    }
  }

  async transform() {
    if (!this.renderer)
      return

    if (!this.animated)
      return

    if (this.previous && this.previous === this.tokens)
      return

    if (this.previous) {
      this.renderer.replace(this.previous)
      this.dispatchEvent(new CustomEvent('onStart'))
      await this.renderer?.render(this.tokens)
      this.dispatchEvent(new CustomEvent('onEnd'))
    }
    else {
      this.renderer.replace(this.tokens)
    }
  }
}

customElements.define('shiki-magic-move-renderer', ShikiMagicMoveRenderer)
