// packages/stream/src/react/renderer.ts
import type { ThemedToken } from '@shikijs/core'
import type { JSX } from 'react'
import type { RecallToken } from '..'
import { objectId } from '@antfu/utils'
import { getTokenStyleObject } from '@shikijs/core'
import { createElement as h, useEffect, useState } from 'react'
import { useEffectEvent } from './utils'

export function ShikiStreamRenderer(
  {
    stream,
    onStreamStart,
    onStreamEnd,
  }: {
    stream: ReadableStream<ThemedToken | RecallToken>
    onStreamStart?: () => void
    onStreamEnd?: () => void
  },
): JSX.Element {
  const [tokens, setTokens] = useState<ThemedToken[]>([])

  const _onStreamStart = useEffectEvent(() => onStreamStart?.())
  const _onStreamEnd = useEffectEvent(() => onStreamEnd?.())

  useEffect(() => {
    setTokens(prevTokens => prevTokens.length ? [] : prevTokens)
    let started = false
    stream.pipeTo(new WritableStream({
      write(token) {
        if (!started) {
          started = true
          _onStreamStart()
        }
        if ('recall' in token)
          setTokens(tokens => tokens.slice(0, -token.recall))
        else
          setTokens(tokens => [...tokens, token])
      },
      close: () => _onStreamEnd(),
    }))
  }, [_onStreamEnd, _onStreamStart, stream])

  return h(
    'pre',
    { className: 'shiki shiki-stream' },
    h(
      'code',
      {},
      tokens.map(token => h('span', { key: objectId(token), style: token.htmlStyle || getTokenStyleObject(token) }, token.content)),
    ),
  )
}

// packages/stream/src/solid/renderer.tsx
/* @jsxImportSource solid-js */

import type { ThemedToken } from '@shikijs/core'
import type { JSX } from 'solid-js'
import type { RecallToken } from '..'
import { getTokenStyleObject } from '@shikijs/core'
import { createEffect, createSignal, For, on, onCleanup } from 'solid-js'

export function ShikiStreamRenderer(props: {
  stream: ReadableStream<ThemedToken | RecallToken> | null
  onStreamStart?: () => void
  onStreamEnd?: () => void
  class?: string
}): JSX.Element {
  const [tokens, setTokens] = createSignal<ThemedToken[]>([])

  createEffect(on(
    () => props.stream,
    (stream) => {
      if (!stream) {
        setTokens(() => [])
        return
      }

      let started = false
      const abortController = new AbortController()
      const { signal } = abortController

      setTokens(() => [])

      const controller = stream.pipeTo(
        new WritableStream({
          write(token) {
            if (signal.aborted)
              return

            if (!started) {
              started = true
              props.onStreamStart?.()
            }
            if ('recall' in token)
              setTokens(ts => ts.slice(0, -token.recall))
            else
              setTokens(ts => [...ts, token])
          },
          close: () => {
            if (!signal.aborted)
              props.onStreamEnd?.()
          },
          abort: () => {
            if (!signal.aborted)
              props.onStreamEnd?.()
          },
        }),
        { signal },
      )
      onCleanup(() => {
        abortController.abort()
        controller.catch(() => {})
      })
    },
  ))

  return (
    <pre class={`shiki shiki-stream${props.class ? ` ${props.class}` : ''}`}>
      <code>
        <For each={tokens()}>
          {token => (
            <span style={token.htmlStyle ?? getTokenStyleObject(token)}>
              {token.content}
            </span>
          )}
        </For>
      </code>
    </pre>
  )
}
